server {
    listen 8080;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
		proxy_pass ${CENTRAL_API_URL};
		proxy_set_header Origin ${CENTRAL_API_URL};
		proxy_hide_header Access-Control-Allow-Origin;
		add_header Access-Control-Allow-Origin $http_origin;
    }
	
	# location /data-app-consumer {
	#	resolver 127.0.0.11 ipv6=off;
	#	set $dataapp_consumer_url be-dataapp-consumer:8084;
	#	proxy_pass https://$dataapp_consumer_url;
		# proxy pass configuration
	#	proxy_redirect off;
	#	proxy_set_header    Upgrade     $http_upgrade;
	#	proxy_set_header    Connection  "upgrade";
	#	proxy_set_header Host $host:$server_port;
	#	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	#	rewrite ^/data-app-consumer/(.*)$ /$1 break;
    #}
	
	#location /data-app-provider {
	#	resolver 127.0.0.11 ipv6=off;
	#	set $dataapp_provider_url be-dataapp-provider:8083;
	#	proxy_pass https://$dataapp_provider_url;
	#	# proxy pass configuration
	#	proxy_redirect off;
	#	proxy_set_header    Upgrade     $http_upgrade;
	#	proxy_set_header    Connection  "upgrade";
	#	proxy_set_header Host $host:$server_port;
	#	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	#	rewrite ^/data-app-provider/(.*)$ /$1 break;
    #}  
}