name: energy-dsp-connector-v2-1-10
services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    networks:
      network-a:
        ipv4_address: 172.18.0.4
    ports:
      - "80:80"
      - "443:443"
      - "8445:8445"  # onenet-dsp-api-a
      - "8446:8446"  # connector-a
      - "8447:8447"  # dsp-connector-ui
      - "8448:8448"  # dozzle
      - "9443:9443"  # minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.onenet-dsp-api-a.address=:8445"
      - "--entrypoints.onenet-dsp-api-a.http.tls=true"
      - "--entrypoints.connector-a.address=:8446"
      - "--entrypoints.connector-a.http.tls=true"
      - "--entrypoints.dsp-connector-ui.address=:8447"
      - "--entrypoints.dsp-connector-ui.http.tls=true"
      - "--entrypoints.dozzle.address=:8448"
      - "--entrypoints.dozzle.http.tls=true"
      - "--entrypoints.minio.address=:9443"
      - "--entrypoints.minio.http.tls=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--certificatesresolvers.resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.resolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.resolver.acme.storage=/acme.json"
      # - "--log.level=DEBUG"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=resolver"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_CREDENTIALS}"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.routers.http-catchall.priority=1"
    dns:
      - 1.1.1.1
      - 8.8.8.8

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    networks:
      - network-a
    volumes:
      - minio_data:/data
    extra_hosts:
      - "${DOMAIN_URL}:172.18.0.4" 
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BROWSER=off
    command: server /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.entrypoints=minio"
      - "traefik.http.routers.minio.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=resolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  onenet-dsp-api-a:
    image: mlafranca/onenet-dsp-api:1.1.8
    container_name: onenet-dsp-api-a
    restart: unless-stopped
    depends_on:
      - connector-a
    networks:
      - network-a
    volumes:
      - ./onenet_dsp_api_a_resources:/config
    extra_hosts:
      - "${DOMAIN_URL}:172.18.0.4" 
    environment:
      - CONNECTOR_URL=${CONNECTOR_A_ENDPOINT_API_URL}
      - CONNECTOR_BASIC_AUTHENTICATION=${CONNECTOR_BASIC_AUTHENTICATION}
      - CENTRALIZED_SERVICES_API_URL=${CENTRALIZED_SERVICES_API_URL}
      - NOTIFICATIONS_ENABLED=${NOTIFICATIONS_ENABLED}
      - NOTIFICATION_MODULE_ENDPOINT=http://4.232.76.64/notification-module/api/v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onenet-dsp-api-a.entrypoints=onenet-dsp-api-a"
      - "traefik.http.routers.onenet-dsp-api-a.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.onenet-dsp-api-a.tls=true"
      - "traefik.http.routers.onenet-dsp-api-a.tls.certresolver=resolver"
      - "traefik.http.services.onenet-dsp-api-a.loadbalancer.server.port=30001"

  connector-a:
    image: mlafranca/dsp-true-connector:0.5.0-2
    container_name: connector-a
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    logging:
      options:
        max-size: "200M"
    networks:
      - network-a
    ports:
      - "8888:2222" # FTP
    extra_hosts:
      - "${DOMAIN_URL}:172.18.0.4" 
    depends_on:
      - mongodb-a
      - minio
    environment:
      - "JDK_JAVA_OPTIONS=-Xmx1024m"
      - CALLBACK_ADDRESS=${CONNECTOR_A_ENDPOINT_API_URL}
      - KEYSTORE_NAME=${CONNECTOR_A_KEYSTORE_NAME}
      - KEY_PASSWORD=${CONNECTOR_A_KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${CONNECTOR_A_KEYSTORE_PASSWORD}
      - KEYSTORE_ALIAS=${CONNECTOR_A_KEYSTORE_ALIAS}
      - DAPS_KEYSTORE_NAME=${DAPS_KEYSTORE_NAME}
      - DAPS_KEYSTORE_PASSWORD=${DAPS_KEYSTORE_PASSWORD}
      - DAPS_KEYSTORE_ALIAS=${KEYSTORE_ALIAS}
      - TRUSTSTORE_NAME=${TRUSTSTORE_NAME}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - S3_EXTERNAL_PRESIGNED_ENDPOINT=${S3_EXTERNAL_PRESIGNED_ENDPOINT}
      - S3_ACCESS_KEY=${MINIO_USER}
      - S3_SECRET_KEY=${MINIO_PASSWORD}
    volumes:
      - ./connector_a_resources:/config
      - ./tc_cert:/cert
      - ./:/home/nobody/ftp
      - tc_a_log:/var/log/tc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.connector-a.entrypoints=connector-a"
      - "traefik.http.routers.connector-a.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.connector-a.tls=true"
      - "traefik.http.routers.connector-a.tls.certresolver=resolver"
      - "traefik.http.services.connector-a.loadbalancer.server.port=8080"

  mongodb-a:
    image: mongo:7.0.31
    container_name: mongodb-a
    restart: unless-stopped
    networks:
      - network-a
    volumes:
      - mongodb-data_a:/data/db
      - mongodb-configdb_a:/data/configdb
    extra_hosts:
      - "${DOMAIN_URL}:172.18.0.4" 

  dsp-connector-ui:
    image: gdimarco/data-space-connector-ui:2.1.9
    container_name: dsp-connector-ui
    restart: always
    networks:
      - network-a
    extra_hosts:
      - "${DOMAIN_URL}:172.18.0.4" 
    volumes:
      - ./connector-ui/nginx-conf/ui-nginx.conf:/etc/nginx/templates/ui-nginx.conf.template
      - ./connector-ui/theme/twineu:/usr/share/nginx/html/img/theme
    environment:
      - APP_PUSH_ENABLED=${PUSH_ENABLED}
      - APP_API_URL=/api
      - CENTRAL_API_URL=${CENTRALIZED_SERVICES_API_URL}
      - APP_NAME=${APP_NAME}
      - APP_BASE_PATH=
      - APP_NATS_ENABLED=${NATS_ENABLED}
      - APP_KAFKA_ENABLED=${KAFKA_ENABLED}
      - APP_ONENET_SETTINGS_ID=1
      - APP_NOTIFICATION_ENABLED=${NOTIFICATIONS_ENABLED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsp-connector-ui.entrypoints=dsp-connector-ui"
      - "traefik.http.routers.dsp-connector-ui.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.dsp-connector-ui.tls=true"
      - "traefik.http.routers.dsp-connector-ui.tls.certresolver=resolver"
      - "traefik.http.services.dsp-connector-ui.loadbalancer.server.port=8080"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - network-a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=dozzle"
      - "traefik.http.routers.dozzle.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=resolver"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

networks:
  network-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  minio_data: {}
  tc_a_log: {}
  mongodb-data_a: {}
  mongodb-configdb_a: {}